### ISSUE TITLE
kded5 crashes beyond repair

### ISSUE THREAD

**Issue by bhush9** [blue-systems/pm-arch#2]
#0  0x00007fedbc6a35f8 in raise () from /usr/lib/libc.so.6
#1  0x00007fedbc6a4a7a in abort () from /usr/lib/libc.so.6
#2  0x00007fedba201f31 in QMessageLogger::fatal(char const*, ...) const () from /usr/lib/libQt5Core.so.5
#3  0x00007fedb02c596e in QXcbConnection::QXcbConnection(QXcbNativeInterface_, bool, unsigned int, char const_) () from /usr/lib/libQt5XcbQpa.so.5
#4  0x00007fedb02cb04d in QXcbIntegration::QXcbIntegration(QStringList const&, int&, char**) () from /usr/lib/libQt5XcbQpa.so.5
#5  0x00007fedb057223d in ?? () from /usr/lib/qt/plugins/platforms/libqxcb.so
#6  0x00007fedbb0b6582 in QPlatformIntegrationFactory::create(QString const&, QStringList const&, int&, char**, QString const&) () from /usr/lib/libQt5Gui.so.5
#7  0x00007fedbb0c27c2 in QGuiApplicationPrivate::createPlatformIntegration() () from /usr/lib/libQt5Gui.so.5
#8  0x00007fedbb0c36dd in QGuiApplicationPrivate::createEventDispatcher() () from /usr/lib/libQt5Gui.so.5
#9  0x00007fedba3f8df6 in QCoreApplication::init() () from /usr/lib/libQt5Core.so.5
#10 0x00007fedba3f8e66 in QCoreApplication::QCoreApplication(QCoreApplicationPrivate&) () from /usr/lib/libQt5Core.so.5
#11 0x00007fedbb0c5439 in QGuiApplication::QGuiApplication(QGuiApplicationPrivate&) () from /usr/lib/libQt5Gui.so.5
#12 0x00007fedbbf3ab7d in QApplication::QApplication(int&, char**, int) () from /usr/lib/libQt5Widgets.so.5
#13 0x00007fedbca23482 in kdemain () from /usr/lib/libkdeinit5_kded5.so
#14 0x00007fedbc690610 in __libc_start_main () from /usr/lib/libc.so.6
#15 0x0000000000400779 in _start ()

**Comment by bhush9** [comment]
Cause for this was ksyncdbusenv not being called..
